#!/usr/bin/ansible-playbook -v
---
# USAGE: ansible-playbook ec2_stop_instances.yml -vvvv

- hosts: localhost
  gather_facts: False
  connection: local
  vars:
    project: ''
  vars_files:
    - vars/aws_config.yml
    - "vars/ec2_instances{{ project }}.yml"
  tasks:
    - name: STOP instances
      tags: stop
      ec2:
        aws_access_key: "{{ access_key }}"
        aws_secret_key: "{{ secret_key }}"
        instance_ids: '{{ instance_ids }}'
        region: '{{ region }}'
        state: stopped
        wait: False
